fix: Add @ts-ignore for Suspense React types conflict
Added @ts-ignore comment before Suspense component to bypass
React types conflict between @types/react versions.

Error: 'Suspense' cannot be used as a JSX component.